name: jaguar_mustache
version: 0.5.0
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_mustache

environment:
  sdk: ">=1.8.0 <2.0.0"

description: Jaguar interceptors to render mustache templates

dependencies:
  mustache: ">=0.2.5+1 <0.3.0"
  jaguar: ^0.6.5
